service_account_id: "your-service-account-id-here"
jwk_json: '{"kty":"RSA","use":"sig","kid":"example-key-id","n":"example-modulus-base64","e":"AQAB","d":"example-private-exponent"}'
platform: "https://your-forgerock-platform.com"
scope: "fr:am:* fr:idm:*"
exp_seconds: 899
proxy: null
verbose: false
output_format: "token"
verify_ssl: true  # true (secure) or false (disable SSL verification)